# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Register.setGeometry(QtCore.QRect(260, 280, 161, 41))
        self.btn_Register.setObjectName("btn_Register")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 170, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 220, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btn_Login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Login.setGeometry(QtCore.QRect(430, 280, 151, 41))
        self.btn_Login.setObjectName("btn_Login")
        self.edt_UserLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_UserLogin.setGeometry(QtCore.QRect(340, 180, 231, 22))
        self.edt_UserLogin.setObjectName("edt_UserLogin")
        self.edt_PasswordLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_PasswordLogin.setGeometry(QtCore.QRect(340, 220, 231, 22))
        self.edt_PasswordLogin.setObjectName("edt_PasswordLogin")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 80, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Register.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.btn_Login.setText(_translate("MainWindow", "Login"))
        self.label_5.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
